import {sequelize} from "../helper/sequelize_config.js"
import { DataTypes } from "sequelize"


const FDM_specs=sequelize.define('FDM',{
    installationSpace:{
        type:DataTypes.STRING,
    },
    surfaceArea:{
        type:DataTypes.STRING,
    },
    driveTech:{
        type:DataTypes.STRING,
    },
    installatingSpaceEnclouser:{
        type:DataTypes.STRING,
    },
    printVolume:{
        type:DataTypes.STRING,
    },
    ZAxisPrintingAccuracy:{
        type:DataTypes.STRING,
    },
    printingAccuracyXYResolution:{
        type:DataTypes.STRING,
    },
    printBedTechnology:{
        type:DataTypes.STRING,
    },
    filamentCompatibility:{
        type:DataTypes.STRING,
    },
    printSpeed:{
        type:DataTypes.STRING,
    },
    nozzleTempurature:{
        type:DataTypes.STRING,
    },
    printTempurature:{
        type:DataTypes.STRING,
    },
    pressureChamberTempurature:{
        type:DataTypes.STRING,
    },
    vibrationSuppresion:{
        type:DataTypes.BOOLEAN,
    },
    automaticPrintBedMeasurement:{
        type:DataTypes.BOOLEAN,
    },
    automaticZOffsetCalibration:{
        type:DataTypes.BOOLEAN,
    },
    liderScannar:{
        type:DataTypes.BOOLEAN,
    },
    doorScannar:{
        type:DataTypes.BOOLEAN,
    },
    circulationFanPressureRoom:{
        type:DataTypes.BOOLEAN,
    },
    supportingComponentCooling:{
        type:DataTypes.BOOLEAN,
    },
    airFiller:{
        type:DataTypes.STRING,
    },
    display:{
        type:DataTypes.STRING,
    },
    dataConnection:{
        type:DataTypes.STRING,
    },
    motherboard:{
        type:DataTypes.STRING,
    },
    printRoomCamera:{
        type:DataTypes.STRING,
    },
    LEDLighting:{
        type:DataTypes.BOOLEAN,
    }
})

export default FDM_specs